version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3028:3028'
    environment:
      - DATABASE_URL=postgres://beermonth_user:nMbltGKxd6ELp238JCyPrvlO2eqxepMu@dpg-co64gh8l5elc73abeemg-a.oregon-postgres.render.com/beermonth
    command: sh -c "npm install && npx prisma migrate dev && npx prisma generate && npm run start"
volumes:
  db_data:
